# Generated by Django 4.2.18 on 2025-02-09 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaboraterequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Collaboration Request', 'verbose_name_plural': 'Collaboration Requests'},
        ),
        migrations.RemoveField(
            model_name='collaboraterequest',
            name='address',
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='address_line1',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='city',
            field=models.CharField(default='Reading', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='postcode',
            field=models.CharField(default='RG20 1EQ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='collaboraterequest',
            name='cuisine_type',
            field=models.CharField(max_length=140),
        ),
    ]
